id: IC6AFFAFC
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T13:28:46+00:00'
last_modified: '2022-06-08T16:23:43.631497+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC16
  title: ཀློང་ཆེན་མཛོད་བདུན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    727E:
      image_group_id: I2PD18488
      title: Volume 1 of klong chen mdzod bdun/
      total_pages: 2
      order: 1
      base_file: 727E.txt
    393C:
      image_group_id: I2PD18489
      title: Volume 2 of klong chen mdzod bdun/
      total_pages: 410
      order: 2
      base_file: 393C.txt
    FB3B:
      image_group_id: I2PD18490
      title: Volume 3 of klong chen mdzod bdun/
      total_pages: 470
      order: 3
      base_file: FB3B.txt
    521B:
      image_group_id: I2PD18491
      title: Volume 4 of klong chen mdzod bdun/
      total_pages: 390
      order: 4
      base_file: 521B.txt
    95C6:
      image_group_id: I2PD18492
      title: Volume 5 of klong chen mdzod bdun/
      total_pages: 666
      order: 5
      base_file: 95C6.txt
    98FF:
      image_group_id: I2PD18493
      title: Volume 6 of klong chen mdzod bdun/
      total_pages: 576
      order: 6
      base_file: 98FF.txt
    '1196':
      image_group_id: I2PD18494
      title: Volume 7 of klong chen mdzod bdun/
      total_pages: 458
      order: 7
      base_file: 1196.txt
    9FCE:
      image_group_id: I2PD18495
      title: Volume 8 of klong chen mdzod bdun/
      total_pages: 362
      order: 8
      base_file: 9FCE.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
