id: IC6AFFAFC
legacy_id: P007056
ocr_import_info:
  bdrc_scan_id: W1AC16
  source: bdrc
  ocr_info:
    timestamp: '2022-07-11T17:38:47'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T15:51:17.260581+00:00'
last_modified: 2022-08-30 23:55:09.368337
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1AC16
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1AC16
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཀློང་ཆེན་མཛོད་བདུན།
  author: ཀློང་ཆེན་རབ་འབྱམས་པ་དྲི་མེད་འོད་ཟེར།
statistics:
  ocr_word_mean_confidence_index: 0.8234692262518294
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I2PD18489:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD18489
      total_pages: 410
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I2PD18489.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.7708036436736884
    legacy_id: v002
  I2PD18490:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD18490
      total_pages: 470
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I2PD18490.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.820255134886666
    legacy_id: v003
  I2PD18492:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD18492
      total_pages: 666
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I2PD18492.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.7978357404406125
    legacy_id: v005
  I2PD18495:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD18495
      total_pages: 362
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I2PD18495.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.8438306138247773
    legacy_id: v008
  I2PD18488:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD18488
      total_pages: 554
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I2PD18488.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9453594848221424
    legacy_id: v001
  I2PD18493:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD18493
      total_pages: 576
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I2PD18493.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.8398469265651121
    legacy_id: v006
  I2PD18494:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD18494
      total_pages: 458
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I2PD18494.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.8515511930893715
    legacy_id: v007
  I2PD18491:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD18491
      total_pages: 390
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I2PD18491.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.859369816202489
    legacy_id: v004
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
