id: P007056
initial_creation_type: ocr
source_metadata:
  id: bdr:W1AC16
  title: ཀློང་ཆེན་མཛོད་བདུན།
  author: ''
  volumes:
    87ca81d2fc1d454d808703ecfb856509:
      image_group_id: I2PD18488
      title: ''
      volume_number: 1
      total_pages: 554
    4d6ba5d3bb60422a89eac77d3ad5ca74:
      image_group_id: I2PD18489
      title: ''
      volume_number: 2
      total_pages: 410
    fdd0ace2e7444ff7a3c227f88271febc:
      image_group_id: I2PD18490
      title: ''
      volume_number: 3
      total_pages: 470
    02aecac314d5403c9e7a458ca6adf0d9:
      image_group_id: I2PD18491
      title: ''
      volume_number: 4
      total_pages: 390
    98e5323d81154a0394d5341d0f92c327:
      image_group_id: I2PD18492
      title: ''
      volume_number: 5
      total_pages: 666
    5e8629988fca4eff8f678605388555b5:
      image_group_id: I2PD18493
      title: ''
      volume_number: 6
      total_pages: 576
    b2b1919bd1e940d5b5cb97b39256ee24:
      image_group_id: I2PD18494
      title: ''
      volume_number: 7
      total_pages: 458
    2b79dfdc2caa461cad4f8291daf40e0b:
      image_group_id: I2PD18495
      title: ''
      volume_number: 8
      total_pages: 362
ebook_metadata:
  title: ཀློང་ཆེན་མཛོད་བདུན།
  author: ''
  sku: P007056
  cover: cover.jpg
  layers:
  - pagination
